# **Lab : 4**
# **Linear Regression**

In [ ]:
# Import Numpy & PyTorch
import numpy as np
import torch

In [ ]:
#single feature x,target,prediction,feature,byes
# generate model

# Target (apples)
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')

#temperature
inputs=np.array([[73],
[91],
[87],
[102],
[69]], dtype='float32') 

# taking random values(theta1)
weight = np.array([[12],
[21],
[18],
[32],
[25]], dtype='float32')

#bias
bias = np.array([[1],[1],[1],[1],[1]],dtype='float32')

# Generate predictions

prediction = (inputs*weight) + bias

print(prediction)
MSE=np.square(np.subtract(targets,prediction)).mean()

print(MSE)


[[ 877.]
 [1912.]
 [1567.]
 [3265.]
 [1726.]]
3854896.8


In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')
# Target (apples)
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')
from torch.utils.data import TensorDataset,DataLoader
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
# print(inputs)
# print(targets)
dataset = TensorDataset(inputs,targets)
# print(dataset[:5])
#divide datasets into batches
train_loader = DataLoader(dataset, batch_size=4, shuffle=True)
# tuple(train_loader)

# generate random values with ean 0 and variance 1
weights= torch.randn(1,3, requires_grad=True)
biass = torch.randn(1, requires_grad=True)

# print(weights)
# print(biass)

def model(X):
  return X @ weights.t() + biass  # '@' - for matrix multiplication

def MSE_loss(predictions, targets):
  diff = predictions - targets
  return torch.sum(diff * diff)/diff.numel() #numel return number of elements in tensor

for x,y in train_loader:
    predictions = model(x)
    print("Prediction is:\n",predictions)
    print("\Actual target is:\n",y)
    print("\nLoss is: ",MSE_loss(predictions,y))

  #training the model
epochs = 100
for i in range(epochs):
  for x,y in train_loader:
    pds = model(x)

    loss = MSE_loss(pds,y)
    loss.backward()
    # Let's update the weights
    with torch.no_grad():
        weights -= weights.grad *1e-5
        biass -= biass.grad * 1e-5
        # Set the gradients to zero
        weights.grad.zero_()
        biass.grad.zero_()
print("Loss: ",loss)

for x,y in train_loader:
  preds= model(x)
  print("\nFinal Prediction is :\n",preds)
  print("\nActual targets are :\n",y)
  break

Prediction is:
 tensor([[-101.6336],
        [-129.8217],
        [-136.3113],
        [-104.0950]], grad_fn=<AddBackward0>)
\Actual target is:
 tensor([[ 56.],
        [ 81.],
        [ 22.],
        [103.]])

Loss is:  tensor(34311.2344, grad_fn=<DivBackward0>)
Prediction is:
 tensor([[-122.3857]], grad_fn=<AddBackward0>)
\Actual target is:
 tensor([[119.]])

Loss is:  tensor(58267.0391, grad_fn=<DivBackward0>)
Loss:  tensor(8.7227, grad_fn=<DivBackward0>)

Final Prediction is :
 tensor([[ 20.5412],
        [120.2469],
        [ 78.0650],
        [ 55.8846]], grad_fn=<AddBackward0>)

Actual targets are :
 tensor([[ 22.],
        [119.],
        [ 81.],
        [ 56.]])


# **LAB 4_1**

In [ ]:
# Import Numpy & PyTorch
import numpy as np
import torch
import torch.nn as nn
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37],[69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69,96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96,70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]],dtype='float32')
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
# Define dataset
train_ds = TensorDataset(inputs,targets)

# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)
next(iter(train_dl))

# Define model
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

# Define loss function
import torch.nn.functional as F
loss_fn = F.mse_loss
loss = loss_fn(model(inputs), targets)
print(loss)

#definr utility function to train the model
def fit(num_epochs,model,loss_fn,opt):
  for epochs in range(num_epochs):
    for xb,yb in train_dl:
      #generate prediction
      pred = model(xb)
      loss = loss_fn(pred, yb)
      #perform gradient descent
      loss.backward()
      opt.step()
      opt.zero_grad()
  print('Training loss: ', loss_fn(model(inputs), targets))
# Train the model for 100 epochs
fit(100, model, loss_fn, opt)

Parameter containing:
tensor([[ 0.5254, -0.4184,  0.5355],
        [ 0.5600, -0.5614, -0.0317]], requires_grad=True)
Parameter containing:
tensor([-0.2777, -0.1341], requires_grad=True)
tensor(7724.2417, grad_fn=<MseLossBackward0>)
Training loss:  tensor(42.2926, grad_fn=<MseLossBackward0>)


In [ ]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.8138,  72.5178],
        [ 84.1646,  99.2739],
        [111.6369, 132.8438],
        [ 30.9859,  49.4864],
        [ 99.4871, 109.3855],
        [ 58.8138,  72.5178],
        [ 84.1646,  99.2739],
        [111.6369, 132.8438],
        [ 30.9859,  49.4864],
        [ 99.4871, 109.3855],
        [ 58.8138,  72.5178],
        [ 84.1646,  99.2739],
        [111.6369, 132.8438],
        [ 30.9859,  49.4864],
        [ 99.4871, 109.3855]], grad_fn=<AddmmBackward0>)

In [ ]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


# **Exercise 1:**
Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want).

In [ ]:
import numpy as np
import torch
inputs = np.array([[73,67,43],
                   [91,88,64],
                   [87,134,58],
                   [102,43,37],
                   [69,96,70]],dtype='float32')
targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]],dtype='float32')
 # Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
print(inputs)
targets = torch.from_numpy(targets)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [ ]:
# Weights and biases
w = torch.randn(1,3,requires_grad =True)
print(w)
b = torch.randn(1,requires_grad=True)
print(b)
# Define the model
def model(x):
  return torch.mm(x,w.t(),out=None) +b
# Generate predictions
# Compare with targets

preds = model(inputs)
print("Prediction :",preds)
print("Targets :",targets)
# MSE loss
# Compute loss
def mse(P,T):
  diff = 0
  i=0
  sum=0
  n=len(T)
  for k in range(0,n):
    i+=1
    diff = T[k] - P[k]
    square = diff*diff
    sum+=square
  mean = sum/i
  return mean

output = mse(preds,targets)
print("Loss :",output)
# Compute gradients
print("Gradient :",output.backward())
# Gradients for weights
print(w)
print(w.grad)
# Gradients for bias
print(b)
print(b.grad)
# Compute gradients
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5
  w.grad.zero_()
  b.grad.zero_()
print(w)
print(b)
# Generate predictions
# Calculate the loss
new_preds = model(inputs)
new_loss = mse(new_preds,targets)
print("New Loss :",new_loss)
# Train for 100 epochs
for i in range(100):
  preds = model(inputs)
  loss = mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w-=w.grad * 1e-5
    b-=b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()
# Calculate loss
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor([[-0.0107, -0.9455, -1.7936]], requires_grad=True)
tensor([1.3342], requires_grad=True)
Prediction : tensor([[-139.9234],
        [-197.6383],
        [-230.3264],
        [-106.7808],
        [-215.7281]], grad_fn=<AddBackward0>)
Targets : tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])
Loss : tensor([71245.2656], grad_fn=<DivBackward0>)
Gradient : None
tensor([[-0.0107, -0.9455, -1.7936]], requires_grad=True)
tensor([[-42071.1133, -48236.9023, -29437.7402]])
tensor([1.3342], requires_grad=True)
tensor([-508.5589])
tensor([[ 0.4100, -0.4631, -1.4993]], requires_grad=True)
tensor([1.3393], requires_grad=True)
New Loss : tensor([30490.8242], grad_fn=<DivBackward0>)
tensor([317.3429], grad_fn=<DivBackward0>)


In [ ]:
 # Imports
import torch.nn as nn
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [ ]:
def model1(x):
  return x @ w.t() +b
preds = model(inputs)
print("Prediction :",preds)
print("Targets :",targets)
loss = nn.MSELoss()
output = loss(preds,targets)
output.backward()
print("Loss :",output)
print(w)
print(w.grad)
print(b)
print(b.grad)
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()
preds = model1(inputs)
loss = mse(preds,targets)
 
print(loss)

Prediction : tensor([[ 62.1440],
        [ 75.3114],
        [126.3755],
        [ 47.6801],
        [ 74.6674]], grad_fn=<AddBackward0>)
Targets : tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])
Loss : tensor(317.3429, grad_fn=<MseLossBackward0>)
tensor([[ 0.2396,  1.0491, -0.6275]], requires_grad=True)
tensor([[ 494.7767, -286.5272, -282.0871]])
tensor([1.3434], requires_grad=True)
tensor([2.0714])
tensor([136.5282], grad_fn=<DivBackward0>)


# **4 Ecxercise 1.1**

**Estimate the value of model parameters(weights and bias) and MSE Loss after training for 1000 epochs.**

In [ ]:
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader

input = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')

target = np.array([[56], [81], [119], [22], [103] ], dtype='float32')

inputs = torch.from_numpy(input)
targets = torch.from_numpy(target)

dataset = TensorDataset(inputs, targets)

# To divide dataset into the batches
train_loader = DataLoader(dataset, batch_size=4, shuffle=True)

# torch,randn generates random value matrix such that mean = 0 and variance = 1

# 1x3 random value matrix
weight = torch.randn(1,3, requires_grad=True)

# 1x1 random value matrix
biass = torch.rand(1, requires_grad=True)

def mse_loss_function(prediction, target):
  difference = prediction - target
  difference_square = difference * difference
  return torch.sum(difference_square) /difference.numel() 



def model(X):
  return X @ weight.T + biass # input matrix and weight matrix multiplication and add bias

for x, y in train_loader:
  prediction = model(x)

  print("Initial Prediction: ", prediction)
  print("Actual: ", y)

  print("Initial Loss: ", mse_loss_function(prediction, y))


# Training

epochs = 1000

for i in range(epochs):

  for x,y in train_loader:
    preds = model(x)
    loss = mse_loss_function(preds, y)

    loss.backward()

    with torch.no_grad():
      weight -= weight.grad * 1e-5
      biass -= biass.grad * 1e-5

      weight.grad.zero_()
      biass.grad.zero_()





# Final
for x, y in train_loader:
  prediction = model(x)

  print()
  print()

  print("Final Prediction: ", prediction)
  print("Actual: ", y)

  print("Final Loss: ", mse_loss_function(prediction, y))

Initial Prediction:  tensor([[-134.8450],
        [ -85.4040],
        [-180.2136],
        [-118.8040]], grad_fn=<AddBackward0>)
Actual:  tensor([[ 81.],
        [103.],
        [ 22.],
        [119.]])
Initial Loss:  tensor(44881.5469, grad_fn=<DivBackward0>)
Initial Prediction:  tensor([[-112.8036]], grad_fn=<AddBackward0>)
Actual:  tensor([[56.]])
Initial Loss:  tensor(28494.6406, grad_fn=<DivBackward0>)


Final Prediction:  tensor([[118.9919],
        [ 57.5586],
        [ 21.5108],
        [102.3506]], grad_fn=<AddBackward0>)
Actual:  tensor([[119.],
        [ 56.],
        [ 22.],
        [103.]])
Final Loss:  tensor(0.7726, grad_fn=<DivBackward0>)


Final Prediction:  tensor([[82.6352]], grad_fn=<AddBackward0>)
Actual:  tensor([[81.]])
Final Loss:  tensor(2.6739, grad_fn=<DivBackward0>)


In [ ]:
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader

input = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')

target = np.array([[56], [81], [119], [22], [103] ], dtype='float32')

inputs = torch.from_numpy(input)
targets = torch.from_numpy(target)

dataset = TensorDataset(inputs, targets)

# To divide dataset into the batches
train_loader = DataLoader(dataset, batch_size=4, shuffle=True)

# torch,randn generates random value matrix such that mean = 0 and variance = 1

# 1x3 random value matrix
weight = torch.randn(1,3, requires_grad=True)

# 1x1 random value matrix
biass = torch.rand(1, requires_grad=True)

def mse_loss_function(prediction, target):
  difference = prediction - target
  difference_square = difference * difference
  return torch.sum(difference_square) /difference.numel() 



def model(X):
  return X @ weight.T + biass # input matrix and weight matrix multiplication and add bias

for x, y in train_loader:
  prediction = model(x)

  print("Initial Prediction: ", prediction)
  print("Actual: ", y)

  print("Initial Loss: ", mse_loss_function(prediction, y))


# Training

epochs = 1000

for i in range(epochs):

  for x,y in train_loader:
    preds = model(x)
    loss = mse_loss_function(preds, y)

    loss.backward()

    with torch.no_grad():
      weight -= weight.grad * 1e-1
      biass -= biass.grad * 1e-1

      weight.grad.zero_()
      biass.grad.zero_()





# Final
for x, y in train_loader:
  prediction = model(x)

  print()
  print()

  print("Final Prediction: ", prediction)
  print("Actual: ", y)

  print("Final Loss: ", mse_loss_function(prediction, y))

Initial Prediction:  tensor([[-17.8731],
        [-12.9354],
        [ -8.5959],
        [ -6.8420]], grad_fn=<AddBackward0>)
Actual:  tensor([[119.],
        [ 22.],
        [ 56.],
        [ 81.]])
Initial Loss:  tensor(7960.8965, grad_fn=<DivBackward0>)
Initial Prediction:  tensor([[-0.8554]], grad_fn=<AddBackward0>)
Actual:  tensor([[103.]])
Initial Loss:  tensor(10785.9492, grad_fn=<DivBackward0>)


Final Prediction:  tensor([[nan],
        [nan],
        [nan],
        [nan]], grad_fn=<AddBackward0>)
Actual:  tensor([[ 22.],
        [103.],
        [ 56.],
        [ 81.]])
Final Loss:  tensor(nan, grad_fn=<DivBackward0>)


Final Prediction:  tensor([[nan]], grad_fn=<AddBackward0>)
Actual:  tensor([[119.]])
Final Loss:  tensor(nan, grad_fn=<DivBackward0>)


In [ ]:
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader

input = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')

target = np.array([[56], [81], [119], [22], [103] ], dtype='float32')

inputs = torch.from_numpy(input)
targets = torch.from_numpy(target)

dataset = TensorDataset(inputs, targets)

# To divide dataset into the batches
train_loader = DataLoader(dataset, batch_size=4, shuffle=True)

# torch,randn generates random value matrix such that mean = 0 and variance = 1

# 1x3 random value matrix
weight = torch.randn(1,3, requires_grad=True)

# 1x1 random value matrix
biass = torch.rand(1, requires_grad=True)

def mse_loss_function(prediction, target):
  difference = prediction - target
  difference_square = difference * difference
  return torch.sum(difference_square) /difference.numel() 



def model(X):
  return X @ weight.T + biass # input matrix and weight matrix multiplication and add bias

for x, y in train_loader:
  prediction = model(x)

  print("Initial Prediction: ", prediction)
  print("Actual: ", y)

  print("Initial Loss: ", mse_loss_function(prediction, y))


# Training

epochs = 1000

for i in range(epochs):

  for x,y in train_loader:
    preds = model(x)
    loss = mse_loss_function(preds, y)

    loss.backward()

    with torch.no_grad():
      weight -= weight.grad * 1e-7
      biass -= biass.grad * 1e-7

      weight.grad.zero_()
      biass.grad.zero_()





# Final
for x, y in train_loader:
  prediction = model(x)

  print()
  print()

  print("Final Prediction: ", prediction)
  print("Actual: ", y)

  print("Final Loss: ", mse_loss_function(prediction, y))

Initial Prediction:  tensor([[-13.9154],
        [-17.9127],
        [  7.2425],
        [ -6.8972]], grad_fn=<AddBackward0>)
Actual:  tensor([[ 22.],
        [119.],
        [103.],
        [ 56.]])
Initial Loss:  tensor(8290.1406, grad_fn=<DivBackward0>)
Initial Prediction:  tensor([[-1.9804]], grad_fn=<AddBackward0>)
Actual:  tensor([[81.]])
Initial Loss:  tensor(6885.7544, grad_fn=<DivBackward0>)


Final Prediction:  tensor([[61.5998],
        [88.6309],
        [95.4873],
        [97.8282]], grad_fn=<AddBackward0>)
Actual:  tensor([[ 56.],
        [ 81.],
        [119.],
        [103.]])
Final Loss:  tensor(167.2964, grad_fn=<DivBackward0>)


Final Prediction:  tensor([[47.6696]], grad_fn=<AddBackward0>)
Actual:  tensor([[22.]])
Final Loss:  tensor(658.9265, grad_fn=<DivBackward0>)


In [ ]:
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader

input = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')

target = np.array([[56], [81], [119], [22], [103] ], dtype='float32')

inputs = torch.from_numpy(input)
targets = torch.from_numpy(target)

dataset = TensorDataset(inputs, targets)

# To divide dataset into the batches
train_loader = DataLoader(dataset, batch_size=4, shuffle=True)

# torch,randn generates random value matrix such that mean = 0 and variance = 1

# 1x3 random value matrix
weight = torch.randn(1,3, requires_grad=True)

# 1x1 random value matrix
biass = torch.rand(1, requires_grad=True)

def mse_loss_function(prediction, target):
  difference = prediction - target
  difference_square = difference * difference
  return torch.sum(difference_square) /difference.numel() 



def model(X):
  return X @ weight.T + biass # input matrix and weight matrix multiplication and add bias

for x, y in train_loader:
  prediction = model(x)

  print("Initial Prediction: ", prediction)
  print("Actual: ", y)

  print("Initial Loss: ", mse_loss_function(prediction, y))


# Training

epochs = 1000

for i in range(epochs):

  for x,y in train_loader:
    preds = model(x)
    loss = mse_loss_function(preds, y)

    loss.backward()

    with torch.no_grad():
      weight -= weight.grad * 1e-5
      biass -= biass.grad * 1e-5

      weight.grad.zero_()
      biass.grad.zero_()





# Final
for x, y in train_loader:
  prediction = model(x)

  print()
  print()

  print("Final Prediction: ", prediction)
  print("Actual: ", y)

  print("Final Loss: ", mse_loss_function(prediction, y))
pred = model(torch.from_numpy(np.array([70, 34, 45], dtype='float32')))
pred


Initial Prediction:  tensor([[-198.6473],
        [-226.7035],
        [-229.3315],
        [-175.7090]], grad_fn=<AddBackward0>)
Actual:  tensor([[103.],
        [119.],
        [ 81.],
        [ 56.]])
Initial Loss:  tensor(90124.1719, grad_fn=<DivBackward0>)
Initial Prediction:  tensor([[-215.0600]], grad_fn=<AddBackward0>)
Actual:  tensor([[22.]])
Initial Loss:  tensor(56197.4648, grad_fn=<DivBackward0>)


Final Prediction:  tensor([[101.2179],
        [ 81.5094],
        [ 20.8060],
        [ 56.9378]], grad_fn=<AddBackward0>)
Actual:  tensor([[103.],
        [ 81.],
        [ 22.],
        [ 56.]])
Final Loss:  tensor(1.4351, grad_fn=<DivBackward0>)


Final Prediction:  tensor([[118.1912]], grad_fn=<AddBackward0>)
Actual:  tensor([[119.]])
Final Loss:  tensor(0.6541, grad_fn=<DivBackward0>)


tensor([31.4602], grad_fn=<AddBackward0>)