# **LAB 3**

# **NB_Classifier_Weather**

In [ ]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [ ]:
weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast', 'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']
temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild', 'Cool','Mild','Mild','Mild','Hot','Mild']
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes', 'Yes','Yes','Yes','Yes','No']

In [ ]:
le = preprocessing.LabelEncoder()
weather_encoded=le.fit_transform(weather)
print("Weather: ", weather_encoded)

temp_encoded=le.fit_transform(temp)
label=le.fit_transform(play)
print("Temp:",temp_encoded)

print("Play:",label)

Weather:  [2 2 0 1 1 1 0 2 2 1 2 0 0 1]
Temp: [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [ ]:
features=tuple(zip(weather_encoded,temp_encoded))
print("Features:",features)

Features: ((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


In [ ]:
model = MultinomialNB()
model.fit(features, label)

MultinomialNB()

In [ ]:
predicted= model.predict([[0,2]]) # 0:Overcast, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]


In [ ]:
predicted= model.predict([[0,1]]) # 0:Overcast, 1:Hot
print("Predicted Value:", predicted)

Predicted Value: [1]


In [ ]:
predicted= model.predict([[2,2]]) # 2:Sunny, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]


**1.5 Exercise: Manually calculate output for the following cases and compare it
with system’s output.**

1.5.1 (1) Will you play if the temperature is ‘Hot’ and weather is ‘overcast’?

In [ ]:
predicted= model.predict([[0,1]]) # 0:overcast, 1:hot
print("Predicted Value:", predicted)

Predicted Value: [1]


1.5.2 (2) Will you play if the temperature is ‘Mild’ and weather is ‘Sunny’?

In [ ]:
predicted= model.predict([[2,2]]) # 0:Sunny, 1:mild
print("Predicted Value:", predicted)

Predicted Value: [1]


# **Gaussian Naive Bayes from datsets**

In [ ]:
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
# ds = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Lab1_Iris dataset.csv')
iris = datasets.load_iris()

In [ ]:
print("Features: ", iris.feature_names)
print("Labels: ", iris.target_names)
print("\nData shape: ", iris.data.shape)
print("Target shape: ", iris.target.shape)

# print("\n\nData: ",iris.data)
# print("\nTarget: ",iris.target)

print("\n\nData type: ",type(iris.data))

new_data = iris.data[50:, :]
new_target = iris.target[50:]

# print data(feature)shape
print("\n\nNew Data shape: ",new_data.shape)
#print data(target)shape
print("New Traget shape: ",new_target.shape)



Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']

Data shape:  (150, 4)
Target shape:  (150,)


Data type:  <class 'numpy.ndarray'>


New Data shape:  (100, 4)
New Traget shape:  (100,)


In [ ]:
from sklearn.model_selection import train_test_split

data_train, data_test, traget_train, target_test = train_test_split(new_data, new_target, test_size=0.30, random_state=5)

In [ ]:
import numpy as np
gnb = GaussianNB()

gnb.fit(data_train, traget_train)
target_pred = gnb.predict(data_test)

In [ ]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.9


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[16,  1],
       [ 2, 11]])

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred)
recall = recall_score(target_test, target_pred)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: 0.8888888888888888
recall: 0.9411764705882353


--------------------------------------------

In [ ]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

iris = datasets.load_iris()

In [ ]:
print("Features: ", iris.feature_names)
print("Labels: ", iris.target_names)
iris.data.shape

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']


(150, 4)

In [ ]:
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(iris.data,
iris.target, test_size = 0.30, random_state = 10)

In [ ]:
import numpy as np
gnb = GaussianNB()

gnb.fit(data_train, target_train)

target_pred = gnb.predict(data_test)

In [ ]:
from sklearn import metrics

print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 1.0


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[14,  0,  0],
       [ 0, 17,  0],
       [ 0,  0, 14]])

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1. 1. 1.]
recall: [1. 1. 1.]


# **Exercise:**

Task 1: Try the algo on Dataset2 - LabelEncoding of features:
and Train test Division 90% − 10%

In [ ]:
# from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [ ]:
datasets = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Lab3_Dataset2.csv')
print("\nData :\n",datasets)


Data :
    Outlook Temp Wind Humidity Class
0        R    H    F   Normal     N
1        R    H    T     High     N
2        O    H    F   Normal     Y
3        S    M    F   Normal     N
4        S    M    F   Normal     Y
5        S    M    T      Low     Y
6        O    C    T   Normal     Y
7        R    C    F   Normal     Y
8        R    C    F      Low     Y
9        S    M    F     High     Y
10       R    M    T     High     Y
11       O    M    T      Low     Y
12       O    H    F   Normal     Y
13       S    M    T   Normal     N


In [ ]:
X = datasets.iloc[ : ,:-1].values
Y = datasets.iloc[ : ,-1].values
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])

datasets.iloc[:,:-1] = X[:,:]
X[:,1] = le.fit_transform(X[:,1])

datasets.iloc[:,:-1] = X[:,:]
X[:,2] = le.fit_transform(X[:,2])

datasets.iloc[:,:-1] = X[:,:]
X[:,3] = le.fit_transform(X[:,3])
print(X)
datasets.iloc[:,:-1] = X[:,:]

[[1 1 0 2]
 [1 1 1 0]
 [0 1 0 2]
 [2 2 0 2]
 [2 2 0 2]
 [2 2 1 1]
 [0 0 1 2]
 [1 0 0 2]
 [1 0 0 1]
 [2 2 0 0]
 [1 2 1 0]
 [0 2 1 1]
 [0 1 0 2]
 [2 2 1 2]]


In [ ]:
print(datasets.head())

  Outlook Temp Wind Humidity Class
0       1    1    0        2     N
1       1    1    1        0     N
2       0    1    0        2     Y
3       2    2    0        2     N
4       2    2    0        2     Y


In [ ]:
outlook_encoder = X[:,0]
print(outlook_encoder)

[1 1 0 2 2 2 0 1 1 2 1 0 0 2]


In [ ]:
temp_encoder = X[:,1]
print(temp_encoder)

[1 1 1 2 2 2 0 0 0 2 2 2 1 2]


In [ ]:
humidity_encoder = X[:,2]
print(humidity_encoder)

[0 1 0 0 0 1 1 0 0 0 1 1 0 1]


In [ ]:
wind_encoder = X[:,3]
print(wind_encoder)

[2 0 2 2 2 1 2 2 1 0 0 1 2 2]


In [ ]:
le = preprocessing.LabelEncoder()
target_encoder = le.fit_transform(datasets['Class'])
print(target_encoder)

[0 0 1 0 1 1 1 1 1 1 1 1 1 0]


In [ ]:
#import the necessary module
from sklearn.model_selection import train_test_split
#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(X,
Y, test_size = 0.10, random_state = 59)


In [ ]:
import numpy as np
gnb = GaussianNB()
#Train the model using the training sets
gnb.fit(data_train, target_train)
#Predict the response for test dataset
target_pred = gnb.predict(data_test)



/usr/local/lib/python3.8/dist-packages/sklearn/naive_bayes.py:489: RuntimeWarning: divide by zero encountered in log
  n_ij = -0.5 * np.sum(np.log(2.0 * np.pi * self.var_[i, :]))
/usr/local/lib/python3.8/dist-packages/sklearn/naive_bayes.py:490: RuntimeWarning: divide by zero encountered in true_divide
  n_ij -= 0.5 * np.sum(((X - self.theta_[i, :]) ** 2) / (self.var_[i, :]), 1)
/usr/local/lib/python3.8/dist-packages/sklearn/naive_bayes.py:490: RuntimeWarning: invalid value encountered in true_divide
  n_ij -= 0.5 * np.sum(((X - self.theta_[i, :]) ** 2) / (self.var_[i, :]), 1)
/usr/local/lib/python3.8/dist-packages/sklearn/naive_bayes.py:490: RuntimeWarning: invalid value encountered in subtract
  n_ij -= 0.5 * np.sum(((X - self.theta_[i, :]) ** 2) / (self.var_[i, :]), 1)


In [ ]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.23076923076923078


In [ ]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)


In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Normal’, and Wind = ’False’?

In [ ]:
features=tuple(zip(outlook_encoder,temp_encoder,humidity_encoder,wind_encoder))
print("Features:",features)
#Create a Classifier
model=MultinomialNB()
# Train the model using the training sets
model.fit(features,target_encoder)



Features: ((1, 1, 2, 0), (1, 1, 0, 1), (0, 1, 2, 0), (2, 2, 2, 0), (2, 0, 2, 0), (2, 0, 1, 1), (0, 0, 2, 1), (1, 2, 2, 0), (1, 0, 1, 0), (2, 2, 0, 0), (1, 2, 0, 1), (0, 2, 1, 1), (0, 1, 2, 0), (2, 2, 2, 1))


MultinomialNB()

In [ ]:
predicted = model.predict([[1,2,2,0]])
print("Predicted Value:", predicted)

Predicted Value: [1]


 What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’,
and Wind = ’True’?

In [ ]:
predicted = model.predict([[2,0,0,1]])
print("Predicted Value:", predicted)

Predicted Value: [0]


# Task 2: Apply algorithm on breast cancer wisconsin dataset - One Hot Encoding of features: and Train test Division 60%-40%

In [ ]:
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()

In [ ]:
df = pd.DataFrame(data=data.data, columns=data.feature_names)
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [ ]:
x = df
x

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [ ]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [ ]:
y = data.target

In [ ]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
#Use One Hot Encoder from scikit learn
onehotencoder = OneHotEncoder()
#reshape the 1-D country array to 2-D as fit_transform expects 2-D and finally fit the object
x = onehotencoder.fit_transform(df.diagnosis.values.reshape(-1,1)).toarray()
print(df.shape[1])

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(data.data,data.target, test_size = 0.4, random_state = 28)
 
# data_train = data_train.T
# data_test = data_test.T
# target_train = target_train.T
# target_test = target_test.T
 
# print("x train: ", data_train.shape)
# print("x test: ", data_test.shape)
# print("y train: ", target_train.shape)
# print("y test: ", target_test.shape)

In [ ]:
import numpy as np
gnb = GaussianNB()
#Train the model using the training sets
gnb.fit(data_train, target_train)
#Predict the response for test dataset
target_pred = gnb.predict(data_test)

In [ ]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.9298245614035088


In [ ]:

from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)


array([[ 73,   8],
       [  8, 139]])

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.90123457 0.94557823]
recall: [0.90123457 0.94557823]
